"""Tencent Yuanbao channel package.

Public API symbols previously importable from ``octop_gateway.channels.yuanbao``
remain available here for backward compatibility.
"""

from __future__ import annotations

import secrets

from octop_gateway.channels.yuanbao.channel import YuanbaoChannel
from octop_gateway.channels.yuanbao.config import YuanbaoConfig, _YuanbaoToken
from octop_gateway.channels.yuanbao.constants import (
    CALLBACK_C2C_SEND_MSG,
    CALLBACK_GROUP_SEND_MSG,
    CMD_AUTH_BIND,
    CMD_INBOUND_MESSAGE,
    CMD_KICKOUT,
    CMD_PING,
    CMD_SEND_C2C_MESSAGE,
    CMD_SEND_GROUP_HEARTBEAT,
    CMD_SEND_GROUP_MESSAGE,
    CMD_SEND_PRIVATE_HEARTBEAT,
    CMD_TYPE_PUSH,
    CMD_TYPE_PUSH_ACK,
    CMD_TYPE_REQUEST,
    CMD_TYPE_RESPONSE,
    CMD_UPDATE_META,
    DEFAULT_API_DOMAIN,
    DEFAULT_WS_URL,
    HEARTBEAT_FINISH,
    HEARTBEAT_RUNNING,
    HERMES_INSTANCE_ID,
    MODULE_BIZ,
    MODULE_CONN_ACCESS,
    MSG_TYPE_FILE,
    MSG_TYPE_IMAGE,
    MSG_TYPE_SOUND,
    MSG_TYPE_TEXT,
    MSG_TYPE_VIDEO,
    RET_ALREADY_AUTH,
    RET_SUCCESS,
    SIGN_TOKEN_PATH,
    TOKEN_EXPIRED_CODES,
    WT_LEN,
    WT_VARINT,
)
from octop_gateway.channels.yuanbao.protocol import (
    _bytes,
    _field,
    _fields_to_dict,
    _get_bytes,
    _get_string,
    _get_varint,
    _message,
    _parse_fields,
    _string,
    _varint,
    build_file_msg_body,
    build_image_msg_body,
    decode_conn_msg,
    decode_status_response,
    encode_auth_bind_payload,
    encode_c2c_message_payload,
    encode_group_heartbeat_payload,
    encode_group_message_payload,
    encode_private_heartbeat_payload,
    encode_push_ack,
    encode_request,
    encode_text_body,
)
from octop_gateway.channels.yuanbao.utils import _compute_signature

__all__ = [
    "CALLBACK_C2C_SEND_MSG",
    "CALLBACK_GROUP_SEND_MSG",
    "CMD_AUTH_BIND",
    "CMD_INBOUND_MESSAGE",
    "CMD_KICKOUT",
    "CMD_PING",
    "CMD_SEND_C2C_MESSAGE",
    "CMD_SEND_GROUP_HEARTBEAT",
    "CMD_SEND_GROUP_MESSAGE",
    "CMD_SEND_PRIVATE_HEARTBEAT",
    "CMD_TYPE_PUSH",
    "CMD_TYPE_PUSH_ACK",
    "CMD_TYPE_REQUEST",
    "CMD_TYPE_RESPONSE",
    "CMD_UPDATE_META",
    "DEFAULT_API_DOMAIN",
    "DEFAULT_WS_URL",
    "HEARTBEAT_FINISH",
    "HEARTBEAT_RUNNING",
    "HERMES_INSTANCE_ID",
    "MODULE_BIZ",
    "MODULE_CONN_ACCESS",
    "MSG_TYPE_FILE",
    "MSG_TYPE_IMAGE",
    "MSG_TYPE_SOUND",
    "MSG_TYPE_TEXT",
    "MSG_TYPE_VIDEO",
    "RET_ALREADY_AUTH",
    "RET_SUCCESS",
    "SIGN_TOKEN_PATH",
    "TOKEN_EXPIRED_CODES",
    "WT_LEN",
    "WT_VARINT",
    "YuanbaoChannel",
    "YuanbaoConfig",
    "_YuanbaoToken",
    "_bytes",
    "_compute_signature",
    "_field",
    "_fields_to_dict",
    "_get_bytes",
    "_get_string",
    "_get_varint",
    "_message",
    "_parse_fields",
    "_string",
    "_varint",
    "build_file_msg_body",
    "build_image_msg_body",
    "decode_conn_msg",
    "decode_status_response",
    "encode_auth_bind_payload",
    "encode_c2c_message_payload",
    "encode_group_heartbeat_payload",
    "encode_group_message_payload",
    "encode_private_heartbeat_payload",
    "encode_push_ack",
    "encode_request",
    "encode_text_body",
    "secrets",
]
